config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root to: 'projects#index'

  resources :projects, only: [:index, :show] do
    resources :tasks do
      collection do
        get 'board'
      end
    end
  end

  post 'tasks/:id/fire/:event', to: 'tasks#fire_event', as: :fire_event
  post 'tasks/:id/:state', to: 'tasks#update_state', as: :update_state

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_and_belongs_to_many :users
  has_many :tasks

  validates_presence_of :title, :description

  def total_members
    users.length
  end

  def total_tasks
    tasks.length
  end

  def all_tasks_by_state
    Task.possible_states.map { |state| [state, self.tasks.with_state(state)] }.to_h
  end

  def find_tasks_by_states(*states)
    states.map { |state| [state, self.tasks.with_state(state)] }.to_h
  end
end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project
  belongs_to :author, class_name: 'User'
  belongs_to :assignee, class_name: 'User'

  validates_presence_of :title, :author, :description, :state

  after_initialize :set_initial_state

  acts_as_taggable

  default_scope -> { order('updated_at DESC') }

  delegate :email, to: :author, prefix: true
  delegate :email, to: :assignee, prefix: true

  state_machine :state, initial: :open do
    # ordering states for task_board
    state :open
    state :in_progress
    state :resolved
    state :reopened
    state :closed

    event :start_progress do
      transition [:open, :reopened] => :in_progress
    end

    event :stop_progress do
      transition :in_progress => :open
    end

    event :resolve do
      transition [:open, :in_progress, :reopened] => :resolved
    end

    event :close do
      transition [:open, :resolved, :reopened, :in_progress] => :closed
    end

    event :reopen do
      transition [:closed, :resolved] => :reopened
    end

  end

  def self.possible_states
    state_machine.states.map(&:name)
  end

  def transition_for_target_state(target_state)
    self.state_transitions.find { |transition| transition.to == target_state }
  end

  private
  def set_initial_state
    self.state ||= :open
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_and_belongs_to_many :projects
  has_many :created_tasks, class_name: 'Task', foreign_key: :author_id
  has_many :assigned_tasks, class_name: 'Task', foreign_key: :assignee_id

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    if current_user.admin?
      @projects = Project.all
    else
      @projects = current_user.projects
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project, only: [:index, :board, :edit, :new, :create, :destroy]
  before_action :set_task, only: [:show, :edit, :update, :destroy, :update_state, :fire_event]
  before_action :correct_user
  before_action :tag_cloud, only: [:board, :index]

  respond_to :js, only: [:update_state]

  def index
    @tasks = @project.tasks
    if params[:tag].present?
      @tasks = @tasks.tagged_with(params[:tag])
    end
    @tasks = @tasks.page params[:page]
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(create_task_params)
    if @task.save
      redirect_to [@task.project, @task], notice: 'Task was successfully created'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to [@task.project, @task], notice: 'Task was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to project_tasks_path(@project), notice: 'Task was successfully destroyed'
  end

  def board
    @tasks_by_states = @project.all_tasks_by_state
  end

  def update_state
    @tasks_by_states = @task.project.find_tasks_by_states @task.state_name, params[:state]

    transition = @task.transition_for_target_state(params[:state])
    if transition && @task.fire_state_event(transition.event)
      flash.now[:success] = "Task '#{@task.title}' is moved to state: #{@task.human_state_name}"
    end
  end

  def fire_event
    @task.fire_state_event(params[:event])
    redirect_to [@task.project, @task]
  end

  private
  def tag_cloud
    @tags = Task.tag_counts_on :tags
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
    redirect_to root_path unless @project.present?
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:estimate, :title, :description, :assignee_id, :tag_list)
  end

  def create_task_params
    task_params.merge(author: current_user, project: @project)
  end

  def correct_user
    redirect_to root_path unless current_user.admin? || current_user.projects.include?(@project)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def members_for_project(project)
    project.users.present? ? project.users.collect(&:email) : ['there are no members']
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  include ActsAsTaggableOn::TagsHelper
  def task_assignee(task)
    task.assignee ? task.assignee_email : 'Not assigned'
  end

  def users_for_assign(project)
    project.users.collect { |user| [user.email, user.id] }
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'YATT', root_path, class: 'navbar-brand' %>
    </div>

    <% if current_user %>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'Admin Dashboard', rails_admin.dashboard_path if current_user.admin? %>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <span class="navbar-text">Signed in as <%= current_user.email %></span>
            </li>
            <li>
              <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </div>
    <% end %>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YetAnotherTaskTracker</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/header' %>

<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/projects/_project.html.erb
<tr>
  <td><%= link_to project.title, board_project_tasks_path(project) %></td>
  <td><%= project.description %></td>
  <td><%= project.total_tasks %></td>
  <td><%= project.total_members %></td>
  <td><%= l project.created_at, format: :date %></td>
</tr>

app/views/projects/index.html.erb
<ol class="breadcrumb">
  <li class="active">Projects</li>
</ol>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Total tasks</th>
      <th>Total members</th>
      <th>Created</th>
    </tr>
  </thead>

  <tbody>
    <%= render @projects %>
  </tbody>
</table>

app/views/tasks/_breadcrumbs.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Projects', root_path %></li>
  <li><%= project.title %></li>
</ol>

<div class="row">
  <ul class="nav nav-pills">
    <li role="presentation">
      <% if board_view %>
          <%= link_to project_tasks_path(project) do %>
              Table <span class="glyphicon glyphicon-list"></span>
          <% end %>
      <% else %>
          <%= link_to board_project_tasks_path(project) do %>
              Board <span class="glyphicon glyphicon-th"></span>
          <% end %>
      <% end %>
    </li>
    <li role="presentation" class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        Members <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <% members_for_project(project).each do |member| %>
            <li><a class="content"><%= member %></a></li>
        <% end %>
      </ul>
    </li>
    <li role="presentation" class="pull-right">
      <%= link_to 'Create new task', new_project_task_path(project), class: '' %></li>
  </ul>
</div>

<hr>

<div class="row tag-cloud">
  <span class="glyphicon glyphicon-tags"> </span>
  <% tag_cloud(tags, %w(label-default)) do |tag, css_class| %>
      <%= link_to tag.name, project_tasks_path(project, tag: tag.name), class: "label  #{params[:tag] == tag.name ? 'label-primary' : css_class}" %>
  <% end %>
</div>
<hr>

app/views/tasks/_form.html.erb
<hr>

<%= form_for([project, task], html: { class: 'form-horizontal' }) do |f| %>

    <div class="form-group">
      <label class="col-sm-4 control-label">
        Project
      </label>

      <div class="col-sm-6">
        <%= link_to project.title, board_project_tasks_path(project) %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-4 control-label">
        Title <span class="required-field">&#42;</span>
      </label>

      <div class="col-sm-6">
        <%= f.text_field :title, class: 'form-control', required: true %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-4 control-label">
        Description <span class="required-field">&#42;</span>
      </label>

      <div class="col-sm-6">
        <%= f.text_area :description, rows: 5, class: 'form-control', required: true %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-4 control-label">
        Estimated time, hrs
      </label>

      <div class="col-sm-6">
        <%= f.number_field :estimate, min: 1, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-4 control-label">
        Assign to
      </label>

      <div class="col-sm-6">
        <%= f.select :assignee_id, users_for_assign(project), { include_blank: true }, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-4 control-label">
        Tags (separated by commas)
      </label>

      <div class="col-sm-6">
        <%= f.text_field :tag_list, class: 'form-control', value: task.tag_list.to_s %>
      </div>
    </div>

    <div class="col-sm-10">
      <div class="form-group btn-group pull-right" role="group">
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to 'Cancel', :back, class: 'btn btn-default' %>
      </div>
    </div>
<% end %>

app/views/tasks/_task.html.erb
<tr>
  <td><%= link_to task.title, [task.project, task] %></td>
  <td><%= task.human_state_name %></td>
  <td><%= task_assignee task %></td>
  <td><%= task.estimate %></td>
  <td><%= raw task.tag_list %></td>
  <td>
    <%= link_to  edit_project_task_path(task.project, task) do %>
        <span class="glyphicon glyphicon-pencil"></span>
    <% end %>
  </td>
</tr>

app/views/tasks/_tasks_column.html.erb
<h4 class="text-center">
  <%= "#{state.to_s.humanize}" %> <span class="badge"> <%= tasks.size %></span>
</h4>

<ul>
  <% tasks.each do |task| %>
      <li class="well draggable-task" id="<%= "#{state}-#{task.id}" %>">
        <%= link_to task.title, [task.project, task] %>
        <br>
        Assigned for: <%= task_assignee task %>
      </li>
  <% end %>
</ul>

app/views/tasks/board.html.erb
<%= render 'breadcrumbs', project: @project, board_view: true, tags: @tags %>

<div class="row" id="tasks-board">
  <div class="col-md-1"></div>
  <% @tasks_by_states .each do |state, tasks| %>
      <div class="col-md-2 droppable-column" id="<%= state %>">
        <div id="tasks-column-<%= state %>">
          <%= render 'tasks_column', state: state, tasks: tasks %>
        </div>
      </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h2 class="text-center">Editing Task</h2>

<%= render 'form', project: @project, task: @task %>

app/views/tasks/index.html.erb
<%= render 'breadcrumbs', project: @project, board_view: false, tags: @tags %>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Title</th>
    <th>State</th>
    <th>Assignee</th>
    <th>Estimate, hrs</th>
    <th>Tags</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <%= render @tasks %>
  </tbody>
</table>

<div class="text-center">
  <%= paginate @tasks %>
</div>

app/views/tasks/new.html.erb
<h2 class="text-center">New Task</h2>

<%= render 'form', project: @project, task: @task %>

app/views/tasks/show.html.erb
<div class="row">
  <div class="col-md-8">
    <h2>
      <%= @task.title %>
    </h2>

    <hr>

    <p>
      <span class="glyphicon glyphicon-tags">    </span>
      <% @task.tag_list.each do |tag| %>
          <span class="label label-info"><%= tag %></span>
      <% end %>
    </p>

    <div class="well well-lg"><%= @task.description %></div>

    <p>
      <strong>State:</strong>
      <%= @task.human_state_name %>
    </p>

    <p>
      <strong>Creator:</strong>
      <%= @task.author_email %>
    </p>

    <p>
      <strong>Assigned to:</strong>
      <%= task_assignee @task %>
    </p>

    <p>
      <strong>Estimated time, hrs:</strong>
      <%= @task.estimate %>
    </p>

    <div class="btn-group pull-right" role="group">
      <%= link_to 'Back', :back, class: 'btn btn-default' %>
      <%= link_to 'Edit', [:edit, @task.project, @task], method: :get, class: 'btn btn-default' %>
      <%= link_to('Delete', [@task.project, @task], method: :delete, class: 'btn btn-default') if current_user == @task.author %>
    </div>
  </div>

  <div class="col-md-4">
    <h4>Available actions:</h4>

    <ul class="action-list">
      <% @task.state_events.each do |event| %>
          <li>
            <%= button_to event.to_s.humanize, fire_event_path(@task, event), method: :post, class: 'btn btn-info' %>
          </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tasks/update_state.js.erb
<% @tasks_by_states.each do |state, tasks| %>
$('#tasks-column-<%= state %>').html("<%= escape_javascript render 'tasks/tasks_column', state: state, tasks: tasks %>");
<% end %>
init_tasks_board();
//$('#flash').html("<%#= escape_javascript render 'layouts/flash' %>");